"Had 5 other commits nuked, fully scaled gif files were exceeding 100MB. I compressed it, but it was still in commit history. Even though the compressed gifs now where present instead of 100MB monstrosities. I needed to do git reset --hard and move back many steps.
Otherwise, ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'github.com:Viktotovich/restaurant-template.git'

This error hindered days of progress"